#!/bin/sh
#
# Copyright (C) 2013 Arthur Vuillard <arthur@hashbang.fr>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ "$1" != "configure" ]
then
    exit 0
fi

# Create SQLite database if needed
sqlite=/var/lib/nagios2mantis/spool.sqlite
if [ ! -f $sqlite ]
then
    mkdir -p $(dirname $sqlite)
    touch $sqlite
    chown nagios:nagios $sqlite "$(dirname $sqlite)"
    chmod 600 $sqlite
fi

# Create inotify file if needed
inotify_file=/var/lib/nagios2mantis/nagios2mantis.inotify
if [ ! -f $inotify_file ]
then
    mkdir -p $(dirname $inotify_file)
    touch $inotify_file
    chown nagios:nagios $inotify_file "$(dirname $inotify_file)"

    # Restart incrond
    invoke-rc.d incron restart
fi

exit 0
